# Generated by Django 3.0.6 on 2021-01-11 20:16

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Proveedor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.IntegerField()),
                ('nombre', models.CharField(max_length=16)),
                ('comentarios', models.TextField()),
            ],
            options={
                'ordering': ['codigo'],
            },
        ),
        migrations.CreateModel(
            name='Factura',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(help_text='Introduce el código de la factura', max_length=32)),
                ('autor', models.CharField(max_length=16)),
                ('fecha_creacion', models.DateField(default=datetime.date.today, verbose_name='Date')),
                ('fecha_vencimiento', models.DateField(blank=True, null=True)),
                ('proveedor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app.Proveedor')),
            ],
            options={
                'ordering': ['-fecha_creacion'],
            },
        ),
    ]
