# Generated by Django 3.0.6 on 2021-01-11 20:27

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='factura',
            name='pdf',
            field=models.FileField(default=django.utils.timezone.now, upload_to='documentos/%Y/%m/%d/'),
            preserve_default=False,
        ),
    ]
