# Generated by Django 3.0.6 on 2021-01-11 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_factura_pdf'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proveedor',
            name='comentarios',
            field=models.TextField(blank=True, null=True),
        ),
    ]
