# Generated by Django 3.0.6 on 2021-01-16 18:02

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20210111_2135'),
    ]

    operations = [
        migrations.AddField(
            model_name='factura',
            name='cantidad',
            field=models.DecimalField(decimal_places=2, default=767.36, max_digits=6, verbose_name='Precio ex. IVA.'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='factura',
            name='observaciones',
            field=models.TextField(default='nada', verbose_name='Observaciones'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='factura',
            name='tipo_iva',
            field=models.IntegerField(default=21, verbose_name='% IVA'),
        ),
        migrations.AlterField(
            model_name='factura',
            name='fecha_creacion',
            field=models.DateField(default=datetime.date.today, verbose_name='Fecha'),
        ),
    ]
